[build]
  command = "npm run build"
  publish = "build"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/blobs"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
